# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MoveAround' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'AFNetworking', '~> 2.5'
  pod 'BDBOAuth1Manager'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'

  # Pods for MoveAround

end
