# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MoveAround' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'AFNetworking', '~> 2.5'
  pod 'BDBOAuth1Manager'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'Parse'
  pod 'MBProgressHUD'
  pod 'ParseFacebookUtilsV4'
  pod 'GooglePlaces'
  pod 'DotsLoading'
  #pod 'JBDatePicker'
  pod 'CalendarDateRangePickerViewController'
end
swift_32 = ['FacebookCore', 'FacebookShare']
post_install do |installer|
  installer.pods_project.targets.each do |target|
        target.build_configurations.each do |configuration|
            # these libs work now only with Swift3.2 in Xcode9
            if swift_32.include? target.name
                configuration.build_settings['SWIFT_VERSION'] = "3.2"
            end
        end
    end
end
